version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    environment:
      - JWT_SECRET=O5JPraBHDtSFc884VoXfu83xdPE2szdrtsuYu0B4ogg=
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
